# Generated by Django 4.0.4 on 2022-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_leaves', '0002_alter_memberleave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberleave',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Leave From'),
        ),
        migrations.AlterField(
            model_name='memberleave',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To Date'),
        ),
    ]
